// Generated by CoffeeScript 1.9.1
(function() {
  var appendCSS;

  appendCSS = function(rule) {
    var styleEle;
    styleEle = document.createElement('style');
    document.head.appendChild(styleEle);
    return styleEle.sheet.insertRule(rule, 0);
  };

  module.exports = appendCSS;

}).call(this);
