// Generated by CoffeeScript 1.10.0
(function() {
  var AppendCss;

  AppendCss = (function() {
    function AppendCss(cssText) {
      this.cssText = cssText;
      this.styleEle = document.createElement('style');
      this.styleEle.textContent = this.cssText;
      document.head.appendChild(this.styleEle);
    }

    AppendCss.prototype.enable = function() {
      return this.styleEle.textContent = this.cssText;
    };

    AppendCss.prototype.disable = function() {
      return this.styleEle.textContent = '';
    };

    AppendCss.prototype.setCss = function(cssText) {
      return this.styleEle.textContent = cssText;
    };

    AppendCss.prototype.dispose = function() {
      document.head.removeChild(this.styleEle);
      return this.cssText = this.styleEle = null;
    };

    return AppendCss;

  })();

  module.exports = AppendCss;

}).call(this);
